server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/home_school_platform?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1 # 配置使用的redis数据库 0-15

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
# classpath*: 代表扫描 classpath 下的文件（包括 java 和 resources 目录）
# classpath*:com/xx/../mapper/*.xml

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: home-school
  endpoint: http://localhost:9000
